export const icons = {
  selectedMarker: require("./selected-marker.png"),
  arrowDown: require("./arrow-down.png"),
  backArrow: require("./back-arrow.png"),
  eyecross: require("./eyecross.png"),
  arrowUp: require("./arrow-up.png"),
  checkmark: require("./check.png"),
  profile: require("./profile.png"),
  dollar: require("./dollar.png"),
  person: require("./person.png"),
  search: require("./search.png"),
  target: require("./target.png"),
  google: require("./google.png"),
  marker: require("./marker.png"),
  close: require("./close.png"),
  rides: require("./rides.png"),
  email: require("./email.png"),
  point: require("./point.png"),
  chat: require("./chat.png"),
  home: require("./home.png"),
  lock: require("./lock.png"),
  star: require("./star.png"),
  map: require("./map.png"),
  out: require("./out.png"),
  pin: require("./pin.png"),
  to: require("./to.png"),
};
